### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by orliesaurus** [solaristhesun/bosskey#1]
Hi Stefan,

I was googling around and found your tool, wanted to reach out via email but it seems like I could only find this github repo:
Anyway I have installed your Bosskey (2020.10b) and when I hit the hotkey it doesn't seem to hide from the system tray. I can only hide the windows from taskbar.
I tried to use it on VLC.exe btw

I'm on Windows10

**Comment by solaristhesun** [comment]
Can you try a different hotkey? Maybe the keys are blocked by another application.

**Comment by orliesaurus** [comment]
Yeah I tried different keys, the icon gets hidden from the task bar but not from the area near the desktop time (the one hidden in the ^ menu), is this normal? I enabled the option to hide it there too but no luck 👍

**Comment by solaristhesun** [comment]
Ah, so the hiding in general works? Just the systay icon of VLC player is not removed. I guess that's normal. I have to check how these icons can be hidden as well. The option in the settings is only for hiding the systray icon of bosskey itself. You could hide the VLC systray icon permanently using the windows settings of the notification area as workaround.

**Comment by orliesaurus** [comment]
ah okay, I thought that option was to remove the icon from the systray for the hidden app. Guess it works then, just a different feature! Thank you for following up.
